### PR TITLE
Add migration + test for long podcast feed URLs

### LINKED ISSUE #81: java.io.IOException: Response code: 500
That`s the only error i get after sucessfull login.

``java.io.IOException: Response code: 500``

### PR DESCRIPTION
**Pull request by JonOfUs**
Fixes #81

Add migration for increasing field size of feed URL to 1000.
Also add test for checking with long feed URL.

Should fix future issues with feed URL length, but it's possible that this doesn't fix already existing issues.

### CODE REVIEW

**Comment by thrillfall** [comment]
@JonOfUs thanks again!
Can you click that "rebase ane merge" button by yourself or do only i see that?

**Comment by JonOfUs** [comment]
I can merge as well. I just never did it in the past because then another person can look over the changes once more.

**Comment by thrillfall** [comment]
I trust you to merge changes on your own. You always add thorough tests and that is all I am looking for during review. I fully trust you to do things right by now

**Comment by thrillfall** [comment]
If you are uncertain then please ask but otherwise consider yourself co-maintainer of this project

**Comment by JonOfUs** [comment]
Alright, thanks for your trust :)

**Pull request merged**
