### PR TITLE
Make result nullable, because null can be returned

### PR DESCRIPTION
**Pull request by pbek**

### CODE REVIEW

**Comment by pbek** [comment]
Seems like the CI tests are currently broken.

**Comment by thrillfall** [comment]
@pbek sorry i added a merge commit to your branch. Can you please remove that and rebase instead? Thanks

**Comment by pbek** [comment]
I have now reset your merge commit and force-pushed to my branch.

**Comment by thrillfall** [comment]
There is yet again a merge commit from  main. Can you please rebase instead of merging main back into your branch?

**Comment by thrillfall** [comment]
Thanks!!

**Pull request merged**
