### PR TITLE
Add support of NC23

### PR DESCRIPTION
**Pull request by JonOfUs**
Tested this with SQLite and MySQL with NC23 instances and AntennaPod Debug. Worked without problems.

### CODE REVIEW

**Comment by thrillfall** [comment]
cool. thanks!
please add nc23 to the test roaster here: https://github.com/thrillfall/nextcloud-gpodder/blob/a9e29e269cfe075f0f746372605a63311917dd0f/.github/workflows/ci.yml#L23

**Comment by thrillfall** [comment]
fixes #50 49

**Comment by JonOfUs** [comment]
Thanks for reminding.
This should be done now.

Should we test php8.0 next to php7.4 since it is supported since Nextcloud 22?

**Comment by JonOfUs** [comment]
Yeah, I'll do this.
Should I do the CHANGELOG.md and v3.2.0 in the info.xml in this PR or open a new one?

**Comment by thrillfall** [comment]
> Yeah, I'll do this. Should I do the CHANGELOG.md and v3.2.0 in the info.xml in this PR or open a new one?

just add it to upcoming section at the top and i'll do the release then

**Comment by JonOfUs** [comment]
Okay, testing with php8.0 seems to be a bit tricky since the composer.lock has requirements not supporting it.
Since I don't know about composer, I'll just roll back this commit and this change can be done later. Do you agree?

**Comment by JonOfUs** [comment]
Done, ready to be merged. Needed the merge commit for the upcoming section in CHANGELOG.md - maybe you can rebase this so that the commit will disappear (if it won't do this by itself).

**Pull request merged**
