### PR TITLE
allign codecheck with maintained nextcloud versions

### PR DESCRIPTION
**Pull request by txt-file**
* remove stable26 as it is end of life
* add stable29 as nextcloud server is currently at 28.0.0 RC1

### CODE REVIEW

**Comment by thrillfall** [comment]
thanks

**Comment by smoothml** [comment]
@thrillfall any update on when this will be merged? Thanks 😄

**Comment by JonOfUs** [comment]
@txt-file could you combine the CI changes (including #164 ) into one PR and also change the supported Nextcloud version in `appinfo/info.xml`? You will have to edit the `<php>` and the `<nextcloud min-version=... max_version=...>` values.

**Comment by nunombispo** [comment]
When will this be merged?

I run a shared Nextcloud server and would like to update to v29 but cannot do so now, since GPodderSync is a very used app.

**Comment by JonOfUs** [comment]
Implemented in #170

**Pull request closed without merging**
